spring:
  profiles:
    active: dev
  thymeleaf:
    mode: HTML
  devtools:
    restart:
      trigger-file: .trigger

book:
  name:互聯網
  author:ggg
  isbn:${random.uuid}
  description:${book.name} ,書不錯
